/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for retromode
**
**	Copyright (c) 2010 LiveForIt Software.
**	MIT License
*/

#include <exec/types.h>
#include <libraries/retromode.h>

#include <interfaces/retromode.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

struct Library * retromodeBase = NULL;
static struct Library * __retromodeBase;

/****************************************************************************/

void retromode_base_constructor(void)
{
    if (retromodeBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __retromodeBase = retromodeBase = (struct Library *)IExec->OpenLibrary("retromode.library", 0L);
    assert(retromodeBase != NULL);
}
__attribute__((section(".ctors.zzzz"))) static void
(*retromode_base_constructor_ptr)(void) USED = retromode_base_constructor;

/****************************************************************************/

void retromode_base_destructor(void)
{
    if (__retromodeBase)
    {
        IExec->CloseLibrary((struct Library *)__retromodeBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*retromode_base_destructor_ptr)(void) USED = retromode_base_destructor;

/****************************************************************************/

