
/* This file was generated by idltool 53.6. Do not edit */

#include "retromode_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _retromode_Obtain,
    _retromode_Release,
    NULL,
    NULL,
    _retromode_retroAllocVideo,
    _retromode_retroFreeVideo,
    _retromode_retroClearVideo,
    _retromode_retroDrawVideo,
    _retromode_retroDmaVideo,
    _retromode_retroSetVideoColor,
    _retromode_retroApplyCopper,
    _retromode_retroOpenScreen,
    _retromode_retroCloseScreen,
    _retromode_retroApplyScreen,
    _retromode_retroPixel,
    _retromode_retroPoint,
    _retromode_retroFlash,
    _retromode_retroCycleColorsUp,
    _retromode_retroCycleColorsDown,
    _retromode_retroBAR,
    _retromode_retroOrBAR,
    _retromode_retroXorBAR,
    _retromode_retroBox,
    _retromode_retroOrBox,
    _retromode_retroXorBox,
    _retromode_RetroShift,
    _retromode_retroCircle,
    _retromode_retroEclipse,
    _retromode_retroOrCircle,
    _retromode_retroXorCircle,
    _retromode_retroScreenColor,
    _retromode_retroOrBlit,
    _retromode_retroAndClear,
    _retromode_retroModeBadVideoSync,
    _retromode_AfterEffectScanline,
    _retromode_AfterEffectAdjustRGB,
    _retromode_retroTriangle,
    _retromode_retroOrTriangle,
    _retromode_retroXorTriangle,
    _retromode_retroLine,
    _retromode_retroOrLine,
    _retromode_retroXorLine,
    (APTR)-1
};

