
/* This file was generated by idltool 53.6. Do not edit */

#include "retromode_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _retromode_Obtain,
    _retromode_Release,
    NULL,
    NULL,
    _retromode_alloc_retoVideo,
    _retromode_free_retroVideo,
    _retromode_clear_retroVideo,
    _retromode_draw_retroVideo,
    _retromode_dma_retroVideo,
    _retromode_set_retroVideoColor,
    _retromode_applyCopper,
    _retromode_retroOpenScreen,
    _retromode_retroCloseScreen,
    _retromode_retroApplyScreen,
    _retromode_retroPixel,
    _retromode_retroPoint,
    _retromode_retroBAR,
    _retromode_retroOrBAR,
    _retromode_retroXorBAR,
    _retromode_retroBox,
    _retromode_retroOrBox,
    _retromode_retroXorBox,
    _retromode_retroCircle,
    _retromode_retroOrCircle,
    _retromode_retroXorCircle,
    _retromode_retroScreenColor,
    _retromode_retroOrBlit,
    _retromode_retroAndClear,
    _retromode_retroModeBadVideoSync,
    _retromode_AfterEffectScanline,
    _retromode_AfterEffectAdjustRGB,
    _retromode_retroTriangle,
    _retromode_retroOrTriangle,
    _retromode_retroXorTriangle,
    _retromode_retroLine,
    (APTR)-1
};

