
/* This file was generated by idltool 53.6. Do not edit */

#include "retromode_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _retromode_Obtain,
    _retromode_Release,
    NULL,
    NULL,
    _retromode_alloc_retoVideo,
    _retromode_free_retroVideo,
    _retromode_clear_retroVideo,
    _retromode_draw_retroVideo,
    _retromode_dma_retroVideo,
    _retromode_set_retroVideoColor,
    _retromode_applyCopper,
    _retromode_retroOpenScreen,
    _retromode_retroCloseScreen,
    _retromode_retroApplyScreen,
    _retromode_retroBAR,
    _retromode_retroScreenColor,
    (APTR)-1
};

