#ifndef RETROMODE_INTERFACE_DEF_H
#define RETROMODE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_RETROMODE_H
#include <libraries/retromode.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct retromodeIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct retromodeIFace *Self);
	ULONG APICALL (*Release)(struct retromodeIFace *Self);
	void APICALL (*Expunge)(struct retromodeIFace *Self);
	struct Interface * APICALL (*Clone)(struct retromodeIFace *Self);
	struct retroVideo * APICALL (*alloc_retoVideo)(struct retromodeIFace *Self, struct Window * window);
	void APICALL (*free_retroVideo)(struct retromodeIFace *Self, struct retroVideo * video);
	void APICALL (*clear_retroVideo)(struct retromodeIFace *Self, struct retroVideo * video);
	void APICALL (*draw_retroVideo)(struct retromodeIFace *Self, struct retroVideo * video);
	void APICALL (*dma_retroVideo)(struct retromodeIFace *Self, struct retroVideo * video);
	void APICALL (*set_retroVideoColor)(struct retromodeIFace *Self, struct retroVideo * video, struct retroRGB * RGB, int color, int from, int to);
	void APICALL (*applyCopper)(struct retromodeIFace *Self, struct retroVideo * video);
	struct retroScreen * APICALL (*retroOpenScreen)(struct retromodeIFace *Self, int width, int height);
	void APICALL (*retroCloseScreen)(struct retromodeIFace *Self, struct retroScreen * screen);
	void APICALL (*retroApplyScreen)(struct retromodeIFace *Self, struct retroScreen * screen, struct retroVideo * video, int offsetx, int oppsety, int videomode);
	void APICALL (*retroBAR)(struct retromodeIFace *Self, struct retroScreen * screen, int x0, int y0, int x1, int y1, unsigned char color);
	void APICALL (*retroScreenColor)(struct retromodeIFace *Self, struct retroScreen * screen, int color, unsigned char r, unsigned char g, unsigned char b);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* RETROMODE_INTERFACE_DEF_H */
