#ifndef INLINE4_RETROMODE_H
#define INLINE4_RETROMODE_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_RETROMODE_H
#include <libraries/retromode.h>
#endif
#include <interfaces/retromode.h>

/* Inline macros for Interface "main" */
#define alloc_retoVideo(window) IRetroMode->alloc_retoVideo((window)) 
#define free_retroVideo(video) IRetroMode->free_retroVideo((video)) 
#define clear_retroVideo(video) IRetroMode->clear_retroVideo((video)) 
#define draw_retroVideo(video) IRetroMode->draw_retroVideo((video)) 
#define dma_retroVideo(video) IRetroMode->dma_retroVideo((video)) 
#define set_retroVideoColor(video, RGB, color, from, to) IRetroMode->set_retroVideoColor((video), (RGB), (color), (from), (to)) 
#define applyCopper(video) IRetroMode->applyCopper((video)) 
#define retroOpenScreen(width, height) IRetroMode->retroOpenScreen((width), (height)) 
#define retroCloseScreen(screen) IRetroMode->retroCloseScreen((screen)) 
#define retroApplyScreen(screen, video, offsetx, oppsety, videomode) IRetroMode->retroApplyScreen((screen), (video), (offsetx), (oppsety), (videomode)) 
#define retroBAR(screen, x0, y0, x1, y1, color) IRetroMode->retroBAR((screen), (x0), (y0), (x1), (y1), (color)) 
#define retroAndClear(screen, x0, y0, x1, y1, and_mask) IRetroMode->retroAndClear((screen), (x0), (y0), (x1), (y1), (and_mask)) 
#define retroScreenColor(screen, color, r, g, b) IRetroMode->retroScreenColor((screen), (color), (r), (g), (b)) 
#define retroOrBlit(bitmap,fromX,fromY,width,height,screen,toX,toY) IRetroMode->retroOrBlit( (bitmap), (fromX), (fromY), (width), (height), (screen), (toX), (toY));
#endif /* INLINE4_RETROMODE_H */
